# Generated by Django 2.2.5 on 2019-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTimePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=10)),
                ('gene_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=80)),
                ('taxonomy', models.CharField(max_length=20)),
                ('protein_fdr_confidence_combined', models.CharField(max_length=10)),
                ('missing_values', models.PositiveSmallIntegerField()),
                ('s_by_n', models.FloatField()),
                ('unique_peptides', models.PositiveSmallIntegerField()),
                ('r1_a', models.FloatField()),
                ('r2_a', models.FloatField()),
                ('a1_a', models.FloatField()),
                ('a2_a', models.FloatField()),
                ('m24_a', models.FloatField()),
                ('pos24_a', models.FloatField()),
                ('neg24_a', models.FloatField()),
                ('m48_a', models.FloatField()),
                ('pos48_a', models.FloatField()),
                ('neg48_a', models.FloatField()),
                ('r1', models.FloatField()),
                ('r2', models.FloatField()),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('m24', models.FloatField()),
                ('pos24', models.FloatField()),
                ('neg24', models.FloatField()),
                ('m48', models.FloatField()),
                ('pos48', models.FloatField()),
                ('neg48', models.FloatField()),
            ],
        ),
    ]
