# Generated by Django 2.2.4 on 2020-03-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(default='', max_length=15, verbose_name='Gene ID')),
                ('accession', models.CharField(default='', max_length=10, verbose_name='Accession')),
                ('description', models.CharField(default='', max_length=80, verbose_name='Description')),
                ('taxonomy', models.CharField(default='', max_length=20, verbose_name='Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='SingleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_gene_id', models.CharField(default='', max_length=200, verbose_name='uniq_gene_id')),
                ('protein_fdr_confidence_combined', models.CharField(default='', max_length=10, verbose_name='Protein FDR Confidence: Combined')),
                ('missing_values', models.FloatField(default=0, verbose_name='Missing values')),
                ('s_by_n', models.FloatField(default=999, verbose_name='Log10(S/N)')),
                ('log2_wt_by_mock', models.FloatField(default=1.0, verbose_name='Log2(WT/Mock)')),
                ('p_wt_by_mock', models.FloatField(default=1.0, verbose_name='p_WT/Mock')),
                ('q_wt_by_mock', models.FloatField(default=1.0, verbose_name='q_WT/Mock')),
                ('log2_delta_vif_by_mock', models.FloatField(default=1.0, verbose_name='Log2(ΔVif/Mock)')),
                ('p_delta_vif_by_mock', models.FloatField(default=1.0, verbose_name='p_ΔVif/Mock')),
                ('q_delta_vif_by_mock', models.FloatField(default=1.0, verbose_name='q_ΔVif/Mock')),
                ('log2_wt_by_delta_vif', models.FloatField(default=1.0, verbose_name='Log2(WT/ΔVif)')),
                ('p_wt_by_delta_vif', models.FloatField(default=1.0, verbose_name='p_WT/ΔVif')),
                ('q_wt_by_delta_vif', models.FloatField(default=1.0, verbose_name='q_WT/ΔVif')),
                ('a_mock', models.FloatField(default=1.0, verbose_name='A_Mock')),
                ('b_mock', models.FloatField(default=1.0, verbose_name='B_Mock')),
                ('c_mock', models.FloatField(default=1.0, verbose_name='C_Mock')),
                ('a_wt', models.FloatField(default=1.0, verbose_name='A_WT')),
                ('b_wt', models.FloatField(default=1.0, verbose_name='B_WT')),
                ('c_wt', models.FloatField(default=1.0, verbose_name='C_WT')),
                ('a_delta_vif', models.FloatField(default=1.0, verbose_name='A_ΔVif')),
                ('b_delta_vif', models.FloatField(default=1.0, verbose_name='B_ΔVif')),
                ('c_delta_vif', models.FloatField(default=1.0, verbose_name='C_ΔVif')),
                ('a_a_mock', models.FloatField(default=0.0, verbose_name='A_Mock')),
                ('a_b_mock', models.FloatField(default=0.0, verbose_name='B_Mock')),
                ('a_c_mock', models.FloatField(default=0.0, verbose_name='C_Mock')),
                ('a_a_wt', models.FloatField(default=0.0, verbose_name='A_WT')),
                ('a_b_wt', models.FloatField(default=0.0, verbose_name='B_WT')),
                ('a_c_wt', models.FloatField(default=0.0, verbose_name='C_WT')),
                ('a_a_delta_vif', models.FloatField(default=0.0, verbose_name='A_ΔVif')),
                ('a_b_delta_vif', models.FloatField(default=0.0, verbose_name='B_ΔVif')),
                ('a_c_delta_vif', models.FloatField(default=0.0, verbose_name='C_ΔVif')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abundances.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='MultiTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_gene_id', models.CharField(default='', max_length=200, verbose_name='uniq_gene_id')),
                ('protein_fdr_confidence_combined', models.CharField(default='', max_length=10, verbose_name='Protein FDR Confidence: Combined')),
                ('missing_values', models.FloatField(default=0, verbose_name='Missing values')),
                ('s_by_n', models.FloatField(default=999, verbose_name='Log10(S/N)')),
                ('r1_a', models.FloatField(default=1.0, verbose_name='Abundance Resting_1')),
                ('r2_a', models.FloatField(default=1.0, verbose_name='Abundance Resting_2')),
                ('a1_a', models.FloatField(default=1.0, verbose_name='Abundance Activated_1')),
                ('a2_a', models.FloatField(default=1.0, verbose_name='Abundance Activated_2')),
                ('m24_a', models.FloatField(default=1.0, verbose_name='Abundance 24h_Mock')),
                ('pos24_a', models.FloatField(default=1.0, verbose_name='Abundance 24h_Pos')),
                ('neg24_a', models.FloatField(default=1.0, verbose_name='Abundance 24h_Neg')),
                ('m48_a', models.FloatField(default=1.0, verbose_name='Abundance 48h_Mock')),
                ('pos48_a', models.FloatField(default=1.0, verbose_name='Abundance 48h_Pos')),
                ('neg48_a', models.FloatField(default=1.0, verbose_name='Abundance 48h_Neg')),
                ('log2_r1a_by_r2a', models.FloatField(default=1.0, verbose_name='Abundance Resting Lg2Ratio')),
                ('log2_a1a_by_a2a', models.FloatField(default=1.0, verbose_name='Abundance Activated Lg2Ratio')),
                ('log2_p24a_by_m24a', models.FloatField(default=1.0, verbose_name='Abundance Positive 24 Lg2Ratio')),
                ('log2_n24a_by_m24a', models.FloatField(default=1.0, verbose_name='Abundance Negative 24 Lg2Ratio')),
                ('log2_p48a_by_m48a', models.FloatField(default=1.0, verbose_name='Abundance Positive 48 Lg2Ratio')),
                ('log2_n48a_by_m48a', models.FloatField(default=1.0, verbose_name='Abundance Negative 48 Lg2Ratio')),
                ('r1', models.FloatField(default=1.0, verbose_name='Resting_1')),
                ('r2', models.FloatField(default=1.0, verbose_name='Resting_2')),
                ('a1', models.FloatField(default=1.0, verbose_name='Activated_1')),
                ('a2', models.FloatField(default=1.0, verbose_name='Activated_2')),
                ('m24', models.FloatField(default=1.0, verbose_name='24h_Mock')),
                ('pos24', models.FloatField(default=1.0, verbose_name='24h_Pos')),
                ('neg24', models.FloatField(default=1.0, verbose_name='24h_Neg')),
                ('m48', models.FloatField(default=1.0, verbose_name='48h_Mock')),
                ('pos48', models.FloatField(default=1.0, verbose_name='48h_Pos')),
                ('neg48', models.FloatField(default=1.0, verbose_name='48h_Neg')),
                ('gene_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abundances.Gene')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gene',
            constraint=models.UniqueConstraint(fields=('gene_id', 'accession', 'description', 'taxonomy'), name='uniq_gene'),
        ),
        migrations.AddConstraint(
            model_name='singletime',
            constraint=models.UniqueConstraint(fields=('gene_id', 'log2_wt_by_mock', 'p_wt_by_mock', 'q_wt_by_mock', 'log2_delta_vif_by_mock', 'p_wt_by_delta_vif', 'q_wt_by_delta_vif', 'a_mock', 'b_mock', 'c_mock', 'a_wt', 'b_wt', 'c_wt', 'a_delta_vif', 'b_delta_vif', 'c_delta_vif'), name='uniq_single_time'),
        ),
        migrations.AddConstraint(
            model_name='multitime',
            constraint=models.UniqueConstraint(fields=('gene_id', 'r1', 'r2', 'a1', 'a2', 'm24', 'pos24', 'neg24', 'm48', 'pos48', 'neg48'), name='uniq_multi_time'),
        ),
    ]
