# Generated by Django 2.2.4 on 2020-02-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gene',
            name='unique_entry',
        ),
        migrations.RemoveField(
            model_name='multitime',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='multitime',
            name='description',
        ),
        migrations.RemoveField(
            model_name='multitime',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='singletime',
            name='accession',
        ),
        migrations.RemoveField(
            model_name='singletime',
            name='description',
        ),
        migrations.RemoveField(
            model_name='singletime',
            name='taxonomy',
        ),
        migrations.AddField(
            model_name='gene',
            name='accession',
            field=models.CharField(default='', max_length=10, verbose_name='Accession'),
        ),
        migrations.AddField(
            model_name='gene',
            name='description',
            field=models.CharField(default='', max_length=80, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='gene',
            name='taxonomy',
            field=models.CharField(default='', max_length=20, verbose_name='Taxonomy'),
        ),
        migrations.AddConstraint(
            model_name='gene',
            constraint=models.UniqueConstraint(fields=('gene_id', 'accession', 'description', 'taxonomy'), name='unique_entry'),
        ),
    ]
