# Generated by Django 2.2.5 on 2019-10-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletimepoint',
            name='a1',
            field=models.FloatField(verbose_name='Activated_1'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='a1_a',
            field=models.FloatField(verbose_name='Abundance Activated_1'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='a2',
            field=models.FloatField(verbose_name='Activated_2'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='a2_a',
            field=models.FloatField(verbose_name='Abundance Activated_2'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='accession',
            field=models.CharField(max_length=10, verbose_name='Accession'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='description',
            field=models.CharField(max_length=80, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='gene_id',
            field=models.CharField(max_length=10, verbose_name='Gene ID'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='m24',
            field=models.FloatField(verbose_name='24h_Mock'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='m24_a',
            field=models.FloatField(verbose_name='Abundance 24h_Mock'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='m48',
            field=models.FloatField(verbose_name='48h_Mock'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='m48_a',
            field=models.FloatField(verbose_name='Abundance 48h_Mock'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='missing_values',
            field=models.PositiveSmallIntegerField(verbose_name='Missing values'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='neg24',
            field=models.FloatField(verbose_name='24h_Neg'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='neg24_a',
            field=models.FloatField(verbose_name='Abundance 24h_Neg'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='neg48',
            field=models.FloatField(verbose_name='48h_Neg'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='neg48_a',
            field=models.FloatField(verbose_name='Abundance 48h_Neg'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='pos24',
            field=models.FloatField(verbose_name='24h_Pos'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='pos24_a',
            field=models.FloatField(verbose_name='Abundance 24h_Pos'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='pos48',
            field=models.FloatField(verbose_name='48h_Pos'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='pos48_a',
            field=models.FloatField(verbose_name='Abundance 48h_Pos'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='protein_fdr_confidence_combined',
            field=models.CharField(max_length=10, verbose_name='Protein FDR Confidence: Combined'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='r1',
            field=models.FloatField(verbose_name='Resting_1'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='r1_a',
            field=models.FloatField(verbose_name='Abundance Resting_1'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='r2',
            field=models.FloatField(verbose_name='Resting_2'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='r2_a',
            field=models.FloatField(verbose_name='Abundance Resting_2'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='s_by_n',
            field=models.FloatField(verbose_name='Log10(S/N)'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='taxonomy',
            field=models.CharField(max_length=20, verbose_name='Taxonomy'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='unique_peptides',
            field=models.PositiveSmallIntegerField(verbose_name='# Unique Peptides'),
        ),
    ]
