# Generated by Django 2.2.4 on 2020-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
        ),
    ]
