# Generated by Django 2.2.4 on 2020-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0002_auto_20200219_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitime',
            name='uniq_gene_id',
            field=models.CharField(default='', max_length=200, verbose_name='uniq_gene_id'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='uniq_gene_id',
            field=models.CharField(default='', max_length=200, verbose_name='uniq_gene_id'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='gene_id',
            field=models.CharField(default='', max_length=20, verbose_name='Gene ID'),
        ),
        migrations.AlterField(
            model_name='timecourse',
            name='gene_id',
            field=models.CharField(default='', max_length=20, verbose_name='Gene ID'),
        ),
    ]
