# Generated by Django 2.2.5 on 2019-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0002_auto_20191031_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=10, verbose_name='Accession')),
                ('gene_id', models.CharField(max_length=10, verbose_name='Gene ID')),
                ('description', models.CharField(max_length=80, verbose_name='Description')),
                ('taxonomy', models.CharField(max_length=20, verbose_name='Taxonomy')),
                ('protein_fdr_confidence_combined', models.CharField(max_length=10, verbose_name='Protein FDR Confidence: Combined')),
                ('missing_values', models.FloatField(verbose_name='Missing values')),
                ('s_by_n', models.FloatField(verbose_name='Log10(S/N)')),
                ('unique_peptides', models.PositiveSmallIntegerField(verbose_name='# Unique Peptides')),
                ('r1_a', models.FloatField(default=1.0, verbose_name='Abundance Resting_1')),
                ('r2_a', models.FloatField(default=1.0, verbose_name='Abundance Resting_2')),
                ('a1_a', models.FloatField(default=1.0, verbose_name='Abundance Activated_1')),
                ('a2_a', models.FloatField(default=1.0, verbose_name='Abundance Activated_2')),
                ('m24_a', models.FloatField(default=1.0, verbose_name='Abundance 24h_Mock')),
                ('pos24_a', models.FloatField(default=1.0, verbose_name='Abundance 24h_Pos')),
                ('neg24_a', models.FloatField(default=1.0, verbose_name='Abundance 24h_Neg')),
                ('m48_a', models.FloatField(default=1.0, verbose_name='Abundance 48h_Mock')),
                ('pos48_a', models.FloatField(default=1.0, verbose_name='Abundance 48h_Pos')),
                ('neg48_a', models.FloatField(default=1.0, verbose_name='Abundance 48h_Neg')),
                ('r1', models.FloatField(verbose_name='Resting_1')),
                ('r2', models.FloatField(verbose_name='Resting_2')),
                ('a1', models.FloatField(verbose_name='Activated_1')),
                ('a2', models.FloatField(verbose_name='Activated_2')),
                ('m24', models.FloatField(verbose_name='24h_Mock')),
                ('pos24', models.FloatField(verbose_name='24h_Pos')),
                ('neg24', models.FloatField(verbose_name='24h_Neg')),
                ('m48', models.FloatField(verbose_name='48h_Mock')),
                ('pos48', models.FloatField(verbose_name='48h_Pos')),
                ('neg48', models.FloatField(verbose_name='48h_Neg')),
            ],
        ),
        migrations.DeleteModel(
            name='SingleTimePoint',
        ),
    ]
