# Generated by Django 3.1.3 on 2022-03-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0002_auto_20200313_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitime',
            name='rest_api',
            field=models.CharField(default='undefined', max_length=200, verbose_name='rest_api'),
        ),
    ]
