# Generated by Django 3.1.3 on 2022-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0003_multitime_rest_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multitime',
            name='rest_api',
            field=models.CharField(default='REST_API', max_length=200, verbose_name='rest_api'),
        ),
    ]
