# Generated by Django 2.2.5 on 2019-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0003_auto_20191102_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTimePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=10, verbose_name='Accession')),
                ('gene_id', models.CharField(max_length=10, verbose_name='Gene ID')),
                ('description', models.CharField(max_length=80, verbose_name='Description')),
                ('taxonomy', models.CharField(max_length=20, verbose_name='Taxonomy')),
                ('protein_fdr_confidence_combined', models.CharField(max_length=10, verbose_name='Protein FDR Confidence: Combined')),
                ('missing_values', models.FloatField(verbose_name='Missing values')),
                ('s_by_n', models.FloatField(verbose_name='Log10(S/N)')),
                ('unique_peptides', models.PositiveSmallIntegerField(verbose_name='# Unique Peptides')),
                ('log2_wt_by_mock', models.FloatField(verbose_name='Log2(WT/Mock)')),
                ('c_delta_viv', models.FloatField(verbose_name='C_ΔVif')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
