# Generated by Django 2.2.5 on 2019-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0004_singletimepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAbundance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=10, verbose_name='Gene ID')),
            ],
        ),
    ]
