# Generated by Django 2.2.4 on 2020-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0005_auto_20200305_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletime',
            name='log2_delta_vif_by_mock',
            field=models.FloatField(default=1.0, verbose_name='Log2(ΔVif/Mock)'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='log2_wt_by_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='Log2(WT/ΔVif)'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='log2_wt_by_mock',
            field=models.FloatField(default=1.0, verbose_name='Log2(WT/Mock)'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='p_delta_vif_by_mock',
            field=models.FloatField(default=1.0, verbose_name='p_ΔVif/Mock'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='p_wt_by_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='p_WT/ΔVif'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='p_wt_by_mock',
            field=models.FloatField(default=1.0, verbose_name='p_WT/Mock'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='q_delta_vif_by_mock',
            field=models.FloatField(default=1.0, verbose_name='q_ΔVif/Mock'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='q_wt_by_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='q_WT/ΔVif'),
        ),
        migrations.AlterField(
            model_name='singletime',
            name='q_wt_by_mock',
            field=models.FloatField(default=1.0, verbose_name='q_WT/Mock'),
        ),
    ]
