# Generated by Django 2.2.5 on 2019-11-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0005_indexabundance'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexabundance',
            name='time_course',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to='abundances.TimeCourse'),
        ),
    ]
