# Generated by Django 2.2.4 on 2020-03-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0006_auto_20200305_0948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexAbundance',
        ),
        migrations.DeleteModel(
            name='SingleTimePoint',
        ),
        migrations.DeleteModel(
            name='TimeCourse',
        ),
    ]
