# Generated by Django 2.2.5 on 2019-11-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0006_indexabundance_time_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletimepoint',
            name='a_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='A_ΔVif'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='a_mock',
            field=models.FloatField(default=1.0, verbose_name='A_Mock'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='a_wt',
            field=models.FloatField(default=1.0, verbose_name='A_WT'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='b_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='B_ΔVif'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='b_mock',
            field=models.FloatField(default=1.0, verbose_name='B_Mock'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='b_wt',
            field=models.FloatField(default=1.0, verbose_name='B_WT'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='c_mock',
            field=models.FloatField(default=1.0, verbose_name='C_Mock'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='c_wt',
            field=models.FloatField(default=1.0, verbose_name='C_WT'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='log2_delta_vif_by_mock',
            field=models.FloatField(default=1.0, verbose_name='Log2(ΔVif/Mock)'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='log2_wt_by_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='Log2(WT/ΔVif)'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='p_delta_vif_by_mock',
            field=models.FloatField(default=1.0, verbose_name='p_ΔVif/Mock'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='p_wt_by_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='p_WT/ΔVif'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='p_wt_by_mock',
            field=models.FloatField(default=1.0, verbose_name='p_WT/Mock'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='q_delta_vif_by_mock',
            field=models.FloatField(default=1.0, verbose_name='q_ΔVif/Mock'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='q_wt_by_delta_vif',
            field=models.FloatField(default=1.0, verbose_name='q_WT/ΔVif'),
        ),
        migrations.AddField(
            model_name='singletimepoint',
            name='q_wt_by_mock',
            field=models.FloatField(default=1.0, verbose_name='q_WT/Mock'),
        ),
        migrations.AlterField(
            model_name='indexabundance',
            name='time_course',
            field=models.IntegerField(verbose_name='TimeCourseID'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='c_delta_viv',
            field=models.FloatField(default=1.0, verbose_name='C_ΔVif'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='log2_wt_by_mock',
            field=models.FloatField(default=1.0, verbose_name='Log2(WT/Mock)'),
        ),
    ]
