# Generated by Django 2.2.5 on 2019-11-08 12:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0007_auto_20191108_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexabundance',
            name='single_time_point',
            field=django_mysql.models.ListCharField(models.IntegerField(default=999999, verbose_name='SingleTimePointID'), default=None, max_length=1000, size=None),
        ),
        migrations.AlterField(
            model_name='indexabundance',
            name='time_course',
            field=django_mysql.models.ListCharField(models.IntegerField(default=999999, verbose_name='TimeCourseID'), default=None, max_length=1000, size=None),
        ),
    ]
