# Generated by Django 2.2.5 on 2019-11-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0008_auto_20191108_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecourse',
            name='exp',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='NUMBER OF EXPERIMENTS'),
        ),
    ]
