# Generated by Django 2.2.5 on 2019-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0009_timecourse_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='singletimepoint',
            name='uniq_gene_id',
            field=models.CharField(default='', max_length=10, verbose_name='uniq gene id'),
        ),
        migrations.AddField(
            model_name='timecourse',
            name='uniq_gene_id',
            field=models.CharField(default='', max_length=10, verbose_name='uniq gene id'),
        ),
        migrations.AlterField(
            model_name='singletimepoint',
            name='gene_id',
            field=models.CharField(default='', max_length=10, verbose_name='Gene ID'),
        ),
        migrations.AlterField(
            model_name='timecourse',
            name='gene_id',
            field=models.CharField(default='', max_length=10, verbose_name='Gene ID'),
        ),
    ]
