# Generated by Django 2.2.5 on 2019-11-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0010_auto_20191108_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecourse',
            name='exp',
        ),
    ]
