# Generated by Django 2.2.5 on 2019-11-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0011_remove_timecourse_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletimepoint',
            name='uniq_gene_id',
            field=models.CharField(default='', max_length=10, verbose_name='uniq_gene_id'),
        ),
        migrations.AlterField(
            model_name='timecourse',
            name='uniq_gene_id',
            field=models.CharField(default='', max_length=10, verbose_name='uniq_gene_id'),
        ),
    ]
