# Generated by Django 2.2.5 on 2019-11-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0012_auto_20191112_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singletimepoint',
            old_name='c_delta_viv',
            new_name='c_delta_vif',
        ),
    ]
