# Generated by Django 2.2.5 on 2019-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0014_auto_20191112_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecourse',
            name='log2_a1a_by_a2a',
            field=models.FloatField(default=1.0, verbose_name='Abundance Activated Lg2Ratio'),
        ),
        migrations.AddField(
            model_name='timecourse',
            name='log2_n24a_by_m24a',
            field=models.FloatField(default=1.0, verbose_name='Abundance Negative 24 Lg2Ratio'),
        ),
        migrations.AddField(
            model_name='timecourse',
            name='log2_n48a_by_m48a',
            field=models.FloatField(default=1.0, verbose_name='Abundance Negative 48 Lg2Ratio'),
        ),
        migrations.AddField(
            model_name='timecourse',
            name='log2_p24a_by_m24a',
            field=models.FloatField(default=1.0, verbose_name='Abundance Positive 24 Lg2Ratio'),
        ),
        migrations.AddField(
            model_name='timecourse',
            name='log2_p48a_by_m48a',
            field=models.FloatField(default=1.0, verbose_name='Abundance Positive 48 Lg2Ratio'),
        ),
        migrations.AddField(
            model_name='timecourse',
            name='log2_r1a_by_r2a',
            field=models.FloatField(default=1.0, verbose_name='Abundance Resting Lg2Ratio'),
        ),
    ]
