# Generated by Django 2.2.5 on 2019-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0015_auto_20191120_1518'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timecourse',
            constraint=models.UniqueConstraint(fields=('gene_id', 'r1', 'r2', 'a1', 'a2', 'm24', 'pos24', 'neg24', 'm48', 'pos48', 'neg48'), name='unique_entry'),
        ),
    ]
