# Generated by Django 2.2.5 on 2019-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0016_auto_20191121_0915'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='singletimepoint',
            constraint=models.UniqueConstraint(fields=('gene_id', 'log2_wt_by_mock', 'p_wt_by_mock', 'q_wt_by_mock', 'log2_delta_vif_by_mock', 'p_wt_by_delta_vif', 'q_wt_by_delta_vif', 'a_mock', 'b_mock', 'c_mock', 'a_wt', 'b_wt', 'c_wt', 'a_delta_vif', 'b_delta_vif', 'c_delta_vif'), name='unique_entry'),
        ),
    ]
