# Generated by Django 2.2.4 on 2020-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0018_auto_20191121_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(default='', max_length=15, verbose_name='Gene ID')),
            ],
        ),
    ]
