# Generated by Django 2.2.4 on 2020-02-17 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0019_gene'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abundances.Gene')),
            ],
        ),
    ]
