# Generated by Django 2.2.4 on 2020-02-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0021_multitime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gene',
            old_name='gene_id',
            new_name='gene',
        ),
    ]
