# Generated by Django 2.2.4 on 2020-02-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abundances', '0022_auto_20200217_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abundances.Gene')),
            ],
        ),
    ]
